routes/web.php
<?php

use App\Http\Controllers\AuthController;
use Illuminate\Support\Str;

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\TasksController;
use App\Http\Controllers\TrackingController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\FamiliesController;

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::post('/login', [AuthController::class, 'login'])->name('login');
Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

/**
 * Usuarios autenticados
 */
Route::middleware(['auth'])->group(function () {

    Route::get('/close-trackings', [TrackingController::class, 'close'])->name('close.tracking');
    Route::get('/tracking', [TrackingController::class, 'index'])->name('tracking');
    Route::post('/tracking/save', [TrackingController::class, 'save'])->name('tracking.save');

    Route::post("/dashboard/tasks/json", ['App\Http\Controllers\\TasksController', 'json'])->name("tasks.json");
    Route::post("/dashboard/tasks/details", ['App\Http\Controllers\\TasksController', 'details'])->name("tasks.details");

    /**
     * Administradores
     */
    Route::group(['middleware' => ['role:Admin']], function () {

        Route::get('/dashboard', [HomeController::class, 'dashboard'])->name('dashboard');
        Route::get('/dashboard/tasks', [TasksController::class, 'index'])->name('tasks');

        foreach (['products', 'families', 'tasks', 'users'] as $resource) {

            $singular = Str::singular($resource);

            Route::get("/dashboard/{$resource}", ['App\Http\Controllers\\' . ucfirst($resource) . 'Controller', 'create'])->name($resource);
            Route::get("/dashboard/{$resource}/create", ['App\Http\Controllers\\' . ucfirst($resource) . 'Controller', 'create'])->name("{$resource}.create");
            Route::get("/dashboard/{$resource}/{". $singular . "}/delete", ['App\Http\Controllers\\' . ucfirst($resource) . 'Controller', 'delete'])->name("{$resource}.delete");
            Route::get("/dashboard/{$resource}/{". $singular . "}", ['App\Http\Controllers\\' . ucfirst($resource) . 'Controller', 'edit'])->name("{$resource}.edit");
            Route::post("/dashboard/{$resource}/save", ['App\Http\Controllers\\' . ucfirst($resource) . 'Controller', 'save'])->name("{$resource}.save");

            if('user' == $singular) {
                Route::get("/dashboard/{$resource}/{". $singular . "}/view", ['App\Http\Controllers\\' . ucfirst($resource) . 'Controller', 'view'])->name("{$resource}.view");
            }

        }
    });
});

app/Models/Tracking.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Support\Str;
use Carbon\Carbon;

class Tracking extends Model
{
    use HasFactory;

    protected $fillable = ['user_id', 'task_id', 'product_id', 'start_time', 'end_time', 'paused'];

    public function task(): HasOne
    {
        return $this->hasOne(Task::class, 'id', 'task_id');
    }

    public function user(): HasOne
    {
        return $this->hasOne(User::class, 'id', 'user_id');
    }

    public function getTimeForTimerAttribute(): string {
        $start_time = Carbon::parse($this->attributes['start_time']);

        /** Obtenemos tiempo pausado */
        $pauses_total = 0;
        $pauses = TrackingDetails::where('tracking_id', $this->id)
            ->whereNotNull('pause_time')
            ->whereNotNull('resume_time')
            ->get();
        foreach ($pauses as $pause) {
            $pause_time = strtotime($pause->pause_time);
            $resume_time = strtotime($pause->resume_time);
            $pauses_total += $resume_time - $pause_time;
        }

        $response = $start_time->addSeconds($pauses_total)->format('Y-m-d H:i:s');

        return $response;
    }

    public function getTimeAttribute(): int
    {
        $total = 0;

        /**
         * Obtenemos tiempo total
         */
        $start = strtotime($this->start_time);
        $end = strtotime($this->end_time);

        if ($this->paused) {
            $pause = TrackingDetails::where('tracking_id', $this->id)
                ->whereNotNull('pause_time')
                ->whereNull('resume_time')
                ->orderBy('id', 'desc')
                ->first();

            if ($pause) {
                $end = strtotime($pause->pause_time);
            }

        }

        $total = $end - $start;

        /**
         * Restamos tiempos de pausa
         */
        $pauses_total = 0;
        $pauses = TrackingDetails::where('tracking_id', $this->id)
            ->whereNotNull('pause_time')
            ->whereNotNull('resume_time')
            ->get();
        foreach ($pauses as $pause) {
            $pause_time = strtotime($pause->pause_time);
            $resume_time = strtotime($pause->resume_time);
            $pauses_total += $resume_time - $pause_time;
        }

        return $total - $pauses_total;
    }
}

resources/views/dashboard.blade.php
@extends('layouts.admin')

@section('content')

@endsection

resources/views/families.blade.php
@extends('layouts.admin')

@section('content')

    <section class="dashboard__items">
        <div class="dashboard__title">
            <label class="dashboard__title--label" for="menu">{{__('Familia de productos')}}</label>
            <a href="{{ route('families.create') }}" class="dashboard__title--link form__button">{{__('Nueva familia')}}</a>
        </div>

        <input type="checkbox" class="dashboard__switch" id="items">
        <ul class="dashboard__list dashboard__element-switch">
            @foreach ($families as $family)
                <li>
                    <a href="{{ route('families.edit', $family) }}" class="dashboard__list--element">
                        <strong>{{ $family->name }}</strong>
                    </a>
                </li>
            @endforeach
        </ul>
    </section>

    @if ( request()->routeIs('families.create') or request()->routeIs('families.edit') )

        <section class="dashboard__item">

            <div class="dashboard__title">
                <label class="dashboard__title--label" for="menu">{{__('Nueva familia')}}</label>

                @if (isset($familyToEdit) )
                    <a onclick="return confirm('¿Estás seguro?')" href="{{ route('families.delete', $familyToEdit) }}" class="dashboard__title--link form__button form__button--cancel">{{__('Borrar')}}</a>
                @endif

            </div>

            <input type="checkbox" class="dashboard__switch" id="item">
            <form class="form dashboard__element-switch" method="post" action="{{ route('families.save') }}">
                @csrf
                <div class="form__group">
                    <input type="text" name="name" id="name" class="form__input" placeholder="{{ __('Nombre') }}" autofocus @if (isset($familyToEdit)) value="{{ $familyToEdit->name }}" @endif />
                </div>

                <div class="form__group">
                    <button type="submit" class="form__button">{{ __('Guardar') }}</button>
                </div>

                @if (isset($familyToEdit))
                    <input type="hidden" name="id" value="{{ $familyToEdit->id }}">
                @endif

            </form>

        </section>

    @endif

@endsection

resources/views/login.blade.php
@extends('layouts.tracking')

@section('content')

    <div class="login">
        <div class="logo">
            <img src="{{ asset('images/logo.png') }}" alt="Logo" loading="lazy">
        </div>

        <div class="window">
            <div class="window__header">{{ __('Acceso trabajador') }}</div>
            <div class="window__content">
                <form class="form" action="{{ route('login') }}" method="post">

                    @csrf

                    @if ($errors->has('email'))
                        <span class="form__message">{{ $errors->first('email') }}</span>
                    @endif

                    <div class="form__group">
                        <!-- <label for="email" class="form__label">{{ __('Correo electrónico') }}</label> -->
                        <input type="email" name="email" id="email" class="form__input" placeholder="{{ __('Correo electrónico') }}" required />
                    </div>

                    <div class="form__group">
                        <!-- <label for="password" class="form__label">{{ __('Contraseña') }}</label> -->
                        <input type="password" name="password" id="password" class="form__input" placeholder="{{ __('Contraseña') }}" required />
                    </div>

                    <div class="form__group">
                        <button type="submit" class="form__button">{{ __('Entrar') }}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/products.blade.php
@extends('layouts.admin')

@section('content')

    <section class="dashboard__items">
        <div class="dashboard__title">
            <label class="dashboard__title--label" for="menu">{{__('Familia de productos')}}</label>
            <a href="{{ route('products.create') }}" class="dashboard__title--link form__button">{{__('Nuevo producto')}}</a>
        </div>

        <input type="checkbox" class="dashboard__switch" id="items">
        <ul class="dashboard__list dashboard__element-switch">
            @foreach ($products as $product)
                <li>
                    <a href="{{ route('products.edit', $product) }}" class="dashboard__list--element">
                        <strong>{{ $product->name }}</strong>
                    </a>
                </li>
            @endforeach
        </ul>
    </section>

    @if ( request()->routeIs('products.create') or request()->routeIs('products.edit') )

        <section class="dashboard__item">

            <div class="dashboard__title">
                <label class="dashboard__title--label" for="menu">{{__('Nuevo producto')}}</label>

                @if (isset($productToEdit) )
                    <a onclick="return confirm('¿Estás seguro?')" href="{{ route('products.delete', $productToEdit) }}" class="dashboard__title--link form__button form__button--cancel">{{__('Borrar')}}</a>
                @endif

            </div>

            <input type="checkbox" class="dashboard__switch" id="item">
            <form class="form dashboard__element-switch" method="post" action="{{ route('products.save') }}">
                @csrf
                <div class="form__group">
                    <input type="text" name="name" id="name" class="form__input" placeholder="{{ __('Nombre') }}" autofocus @if (isset($productToEdit)) value="{{ $productToEdit->name }}" @endif />
                </div>

                <div class="form__group">
                    <select name="family_id" id="family_id" class="form__input">

                    @foreach ($families as $family)
                        <option value="{{$family->id}}" @if (isset($productToEdit) && $productToEdit->family_id == $family->id ) selected @endif >{{ $family->name }}</option>
                    @endforeach

                    </select>
                </div>

                <div class="form__group">
                    <button type="submit" class="form__button">{{ __('Guardar') }}</button>
                </div>

                @if (isset($productToEdit))
                    <input type="hidden" name="id" value="{{ $productToEdit->id }}">
                @endif

            </form>

        </section>

    @endif

@endsection

resources/views/tasks.blade.php
@extends('layouts.admin')

@section('content')

    <section class="dashboard__items">
        <div class="dashboard__title">
            <label class="dashboard__title--label" for="menu">{{__('Tareas')}}</label>
            <a href="{{ route('tasks.create') }}" class="dashboard__title--link form__button">{{__('Nueva tarea')}}</a>
        </div>

        <input type="checkbox" class="dashboard__switch" id="items">
        <ul class="dashboard__list dashboard__element-switch">
            @foreach ($tasks as $task)
                <li>
                    <a href="{{ route('tasks.edit', $task) }}" class="dashboard__list--element">
                        <strong>{{ $task->name }}</strong>
                        <span class="dashboard__list--label">{!! $task->family->name ?? '<em>Sin familia</em>' !!}</span>
                    </a>
                </li>
            @endforeach
        </ul>
    </section>

    @if ( request()->routeIs('tasks.create') or request()->routeIs('tasks.edit') )

        <section class="dashboard__item">

            <div class="dashboard__title">
                <label class="dashboard__title--label" for="menu">{{__('Nueva tarea')}}</label>

                @if (isset($taskToEdit) )
                    <a onclick="return confirm('¿Estás seguro?')" href="{{ route('tasks.delete', $taskToEdit) }}" class="dashboard__title--link form__button form__button--cancel">{{__('Borrar')}}</a>
                @endif

            </div>

            <input type="checkbox" class="dashboard__switch" id="item">
            <form class="form dashboard__element-switch" method="post" action="{{ route('tasks.save') }}">
                @csrf

                <div class="form__group">
                    <select name="family_id" id="family_id" class="form__input">

                    <option value="0">{{ __('Sin familia' ) }}</option>
                    @foreach ($families as $family)
                        <option value="{{$family->id}}" @if (isset($taskToEdit) && $taskToEdit->family_id == $family->id ) selected @endif >{{ $family->name }}</option>
                    @endforeach

                    </select>
                </div>

                <div class="form__group">
                    <input type="text" name="name" id="name" class="form__input" placeholder="{{ __('Nombre') }}" autofocus @if (isset($taskToEdit)) value="{{ $taskToEdit->name }}" @endif />
                </div>

                <div class="form__group">
                    <button type="submit" class="form__button">{{ __('Guardar') }}</button>
                </div>

                @if (isset($taskToEdit))
                    <input type="hidden" name="id" value="{{ $taskToEdit->id }}">
                @endif

            </form>

        </section>

    @endif

@endsection

resources/views/timers.blade.php
@extends('layouts.admin')

@section('content')

    <section class="dashboard__items">
        <div class="dashboard__title">
            <label class="dashboard__title--label" for="menu">{{__('Usuarios')}}</label>
            <a href="{{ route('users.create') }}" class="dashboard__title--link form__button">{{__('Nuevo usuario')}}</a>
        </div>

        <input type="checkbox" class="dashboard__switch" id="items">
        <ul class="dashboard__list dashboard__element-switch">

            @foreach ($users as $user)
                <li>
                    <a href="{{ route('users.edit', $user) }}" class="dashboard__list--element @if (isset($userToEdit) && $userToEdit->id == $user->id) active @endif">
                        <strong>{{ $user->name }}</strong>
                        <span class="dashboard__list--label">{{ $user->email }}</span>
                        <span class="dashboard__list--label">{{ $user->hours_per_month }} h.</span>
                        <span class="dashboard__list--label">{{ $user->salary }} €</span>
                    </a>
                </li>
            @endforeach

        </ul>
    </section>


        <section class="dashboard__item">

            <form class="dashboard__title dashboard__title--form" method="get" action="{{ route('users.view', $userToEdit) }}">
                <label class="dashboard__title--label" for="menu">{{__('Histórico')}}</label>

                <label>{{__('Desde')}}</label>
                <input type="date" class="form__input" id="date_from" name="date_from" value="{{ request()->get('date_from') }}" placeholder="{{ __('Desde') }}">

                <label>{{__('Hasta')}}</label>
                <input type="date" class="form__input" id="date_to" name="date_to" value="{{ request()->get('date_to') }}" placeholder="{{ __('Hasta') }}">

                <select class="form__select populate-tasks" id="family" name="family">
                    <option value="">{{ __('Seleccione familia') }}</option>
                    @foreach ($families as $family)
                        <option value="{{$family->id}}" @if (request()->get('family') == $family->id) selected @endif>{{ $family->name }}</option>
                    @endforeach
                </select>

                <button type="submit" class="dashboard__title--link form__button form__button--success">{{__('Filtrar')}}</button>

                <input type="submit" class="dashboard__title--link form__button form__button--warning" name="export" value="{{__('Exportar')}}"></button>

                <a href="{{ route('users.edit', $userToEdit) }}" class="dashboard__title--link form__button">{{__('Volver')}}</a>

            </form>

            <input type="checkbox" class="dashboard__switch" id="item">

            <h1 class="trackings__title">{{ $userToEdit->name }}</h1>

            @if ($trackings)

                <ul class="dashboard__list dashboard__element-switch dashboard__timers">

                    @foreach($trackings as $tracking)

                        <li>
                            <span class="dashboard__list--element">
                                <span class="dashboard__list--label">{{ $tracking->id }}</span>
                                <strong>{{ $tracking->task->family->name ?? 'Sin familia' }}</strong>
                                <span class="dashboard__list--label"><strong>{{ $tracking->task->name  ?? 'Sin tarea' }}</strong></span>
                                <span class="dashboard__list--label">{{ gmdate("H:i:s", $tracking->time) }}</span>
                            </span>
                        </li>

                    @endforeach

                    <li>
                        <span class="dashboard__list--element">
                            <strong>Total</strong>
                            <span class="dashboard__list--label">{{ gmdate("H:i:s", $total) }}</span>
                        </span>
                    </li>

                </ul>

            @endif


        </section>

@endsection

resources/views/tracking.blade.php
@extends('layouts.tracking')

@section('content')

    <form class="form @if ($actual_task != null) tracking-active @endif" method="post" action="{{ route('tracking.save') }}" >
        @csrf

        <div class="block">
            <h2 class="block__header">{{__('Seleccionar proceso')}}</h2>
            <div class="block__content">
            <select class="form__select populate-tasks" id="family_id" name="family_id" data-url="{{ route('tasks.json') }}" data-destination="#task_id" required>
                <option value="">{{ __('Seleccione proceso') }}</option>
                @foreach ($families as $family)
                    <option value="{{$family->id}}" @if ($actual_task && $actual_task->family_id == $family->id) selected @endif>{{ $family->name }}</option>
                @endforeach
            </select>
            </div>
        </div>

        <div class="block">
            <h2 class="block__header">{{__('Tarea a realizar')}}</h2>
            <div class="block__content">
            <select class="form__select" id="task_id" name="task_id" required>
                <option value="">{{ __('Debe seleccionar proceso') }}</option>
            </select>
            </div>
        </div>

        <div class="block">
            <div class="block__content">
            <button class="form__button form_button--start">{{ __('Iniciar') }}</button>
            </div>

            <input type="hidden" name="type" value="start" />
        </div>
    </form>

    @if ($actual_task)
    <form class="form" method="post" action="{{ route('tracking.save') }}">
        @csrf

        @if (!$actual_task)
        <div class="block">
            <h2 class="block__header">{{__('Seleccionar proceso')}}</h2>
            <div class="block__content">
                <select class="form__select populate-tasks" id="family_id" name="family_id" data-url="{{ route('tasks.json') }}" data-destination="#task_id" required>
                    <option value="">{{ __('Seleccione proceso') }}</option>
                    @foreach ($families as $family)
                        <option value="{{$family->id}}" @if ($actual_task && $actual_task->family_id == $family->id) selected @endif>{{ $family->name }}</option>
                    @endforeach
                </select>
            </div>
        </div>

        <div class="block">
            <h2 class="block__header">{{__('Tarea a realizar')}}</h2>
            <div class="block__content">
                <select class="form__select" id="task_id" name="task_id" required>
                    <!-- @foreach ($tasks as $task)
                        <option value="{{$task->id}}" @if ($actual_task && $actual_task->task_id == $task->id) selected @endif>{{ $task->name }}</option>
                    @endforeach -->
                </select>
            </div>
        </div>
        @endif

        <div class="block">

            <div class="block__content">
                @if (!$actual_task)

                    <button class="form__button form_button--start">{{ __('Iniciar') }}</button>

                @else

                    <button class="form__button form_button--stop @if ($actual_task != null && $actual_task->paused) tracking-paused @endif">{{ __('Parar') }}</button>

                    <input type="hidden" name="id" value="{{ $actual_task->id }}" />

                    @if ($actual_task != null && $actual_task->paused)
                        <div class="timer" id="timer-paused">{{ gmdate("H:i:s", $actual_task->time) }}</div>
                    @else
                        <div class="timer" id="timer"></div>
                    @endif

                    <div class="timer__info">
                        <strong>{{ __('Tarea actual:') }}</strong>
                        <span>{{ $actual_task->task->family->name }}</span>
                        <em>{{ $actual_task->task->name }}</em>
                    </div>

                @endif
            </div>

            <input type="hidden" name="type" value="@if (!$actual_task)start @else stop @endif" />

        </div>
    </form>
    @endif

    @if ($actual_task != null)

        <div class="timer__buttons">

            <form class="form form--row" method="post" action="{{ route('tasks.details') }}">
                @csrf
                @if ($actual_task->paused)
                    <button class="form__button timer__button--resume no-wrap" id="resume">{{ __('Reanudar') }}</button>
                    <button class="form__button timer__button--new no-wrap" id="new-tracking">{{ __('Nueva tarea') }}</button>
                @else
                    <button class="form__button timer__button--pause" id="pause">{{ __('Pausar') }}</button>
                @endif

                <input type="hidden" name="id" value="{{ $actual_task->id }}" />
            </form>

        </div>

        <script>  const paused = @if ($actual_task->paused) true @else false @endif; </script>

    @endif

    @if (!empty($paused_trackings) && count($paused_trackings) > 0)

        <h4 class="dashboard__title" style="margin-top: 25px;">{{__('Procesos pausados')}}</h4>

        <ul class="dashboard__list dashboard__list--paused-trackings" style="padding-bottom: 25px;">
            @foreach ($paused_trackings as $tracking)
                <li>

                    <strong class="dashboard__list--label">{{ $tracking->task->family->name }}<br />{{ $tracking->task->name }}</strong>
                    <span class="dashboard__list--label"><small>{{ __('Tiempo') }}</small><br />{{ gmdate("H:i:s", $tracking->time) }}</span>
                    <span class="dashboard__list--label"><small>{{ __('Inicio') }}</small><br />{{ date('H:i:s', strtotime($tracking->start_time)) }}</span>
                    <a href="{{ route('tracking', ['id' => $tracking->id]) }}" class="dashboard__title--link form__button">{{__('Reanudar')}}</a>

                </li>
            @endforeach
        </ul>
    @endif

@endsection

resources/views/users.blade.php
@extends('layouts.admin')

@section('content')

    <section class="dashboard__items">
        <div class="dashboard__title">
            <label class="dashboard__title--label" for="menu">{{__('Usuarios')}}</label>
            <a href="{{ route('users.create') }}" class="dashboard__title--link form__button">{{__('Nuevo usuario')}}</a>
        </div>

        <input type="checkbox" class="dashboard__switch" id="items">
        <ul class="dashboard__list dashboard__element-switch">

            @foreach ($users as $user)
                <li>
                    <a href="{{ route('users.edit', $user) }}" class="dashboard__list--element @if (isset($userToEdit) && $userToEdit->id == $user->id) active @endif">
                        <strong>{{ $user->name }}</strong>
                        <span class="dashboard__list--label">{{ $user->email }}</span>
                        <span class="dashboard__list--label">{{ $user->hours_per_month }} h.</span>
                        <span class="dashboard__list--label">{{ $user->salary }} €</span>
                    </a>
                </li>
            @endforeach

        </ul>
    </section>

    @if ( request()->routeIs('users.create') or request()->routeIs('users.edit') )

        <section class="dashboard__item">

            <div class="dashboard__title">
                <label class="dashboard__title--label" for="menu">{{__('Nuevo trabajador')}}</label>

                @if (isset($userToEdit))
                    <a href="{{ route('users.view', $userToEdit) }}" class="dashboard__title--link form__button">{{__('Histórico')}}</a>
                @endif

                @if (isset($userToEdit) && $userToEdit->id != auth()->user()->id)
                    <a onclick="return confirm('¿Estás seguro?')" href="{{ route('users.delete', $userToEdit) }}" class="dashboard__title--link form__button form__button--cancel">{{__('Borrar')}}</a>
                @endif
            </div>

            <input type="checkbox" class="dashboard__switch" id="item">

            <form class="form dashboard__element-switch" method="post" action="{{ route('users.save') }}">

                @csrf

                <div class="form__group">
                    <input type="text" name="name" id="name" class="form__input" placeholder="{{ __('Nombre') }}" required autofocus @if (isset($userToEdit)) value="{{ $userToEdit->name }}" @endif />
                </div>

                <div class="form__group">
                    <input type="email" name="email" id="email" class="form__input" placeholder="{{ __('Email') }}" required @if (isset($userToEdit)) value="{{ $userToEdit->email }}" @endif />
                </div>

                <div class="form__group">
                    <input type="password" name="password" id="password" class="form__input" placeholder="{{ __('Contraseña') }}" />
                </div>

                <div class="form__group">
                    <input type="text" name="hours_per_month" id="hours_per_month" class="form__input" placeholder="{{ __('Horas mensuales') }}" required @if (isset($userToEdit)) value="{{ $userToEdit->hours_per_month }}" @endif />
                </div>

                <div class="form__group">
                    <input type="text" name="salary" id="salary" class="form__input" placeholder="{{ __('Salario') }}" required @if (isset($userToEdit)) value="{{ $userToEdit->salary }}" @endif />
                </div>

                <div class="form__group">
                    <select name="role" id="role" class="form__input" required>

                        @foreach ($roles as $role)
                            <option value="{{ $role->name }}" @if (isset($userToEdit) && $userToEdit->hasRole($role->name)) selected @endif>{{ $role->name }}</option>
                        @endforeach

                    </select>
                </div>

                <div class="form__group">
                    <button type="submit" class="form__button">{{ __('Guardar') }}</button>
                </div>

                @if (isset($userToEdit))
                    <input type="hidden" name="id" value="{{ $userToEdit->id }}">
                @endif

            </form>



        </section>

    @endif

@endsection