routes/web.php
<?php

use App\Http\Controllers\AuthController;
use Illuminate\Support\Str;

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\TasksController;
use App\Http\Controllers\TrackingController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\FamiliesController;

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::post('/login', [AuthController::class, 'login'])->name('login');
Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

/**
 * Usuarios autenticados
 */
Route::middleware(['auth'])->group(function () {

    Route::get('/close-trackings', [TrackingController::class, 'close'])->name('close.tracking');
    Route::get('/tracking', [TrackingController::class, 'index'])->name('tracking');
    Route::post('/tracking/save', [TrackingController::class, 'save'])->name('tracking.save');

    Route::post("/dashboard/tasks/json", ['App\Http\Controllers\\TasksController', 'json'])->name("tasks.json");
    Route::post("/dashboard/tasks/details", ['App\Http\Controllers\\TasksController', 'details'])->name("tasks.details");

    /**
     * Administradores
     */
    Route::group(['middleware' => ['role:Admin']], function () {

        Route::get('/dashboard', [HomeController::class, 'dashboard'])->name('dashboard');
        Route::get('/dashboard/tasks', [TasksController::class, 'index'])->name('tasks');

        foreach (['products', 'families', 'tasks', 'users'] as $resource) {

            $singular = Str::singular($resource);

            Route::get("/dashboard/{$resource}", ['App\Http\Controllers\\' . ucfirst($resource) . 'Controller', 'create'])->name($resource);
            Route::get("/dashboard/{$resource}/create", ['App\Http\Controllers\\' . ucfirst($resource) . 'Controller', 'create'])->name("{$resource}.create");
            Route::get("/dashboard/{$resource}/{". $singular . "}/delete", ['App\Http\Controllers\\' . ucfirst($resource) . 'Controller', 'delete'])->name("{$resource}.delete");
            Route::get("/dashboard/{$resource}/{". $singular . "}", ['App\Http\Controllers\\' . ucfirst($resource) . 'Controller', 'edit'])->name("{$resource}.edit");
            Route::post("/dashboard/{$resource}/save", ['App\Http\Controllers\\' . ucfirst($resource) . 'Controller', 'save'])->name("{$resource}.save");

            if('user' == $singular) {
                Route::get("/dashboard/{$resource}/{". $singular . "}/view", ['App\Http\Controllers\\' . ucfirst($resource) . 'Controller', 'view'])->name("{$resource}.view");
            }

        }
    });
});

app/Models/Tracking.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Support\Str;
use Carbon\Carbon;

class Tracking extends Model
{
    use HasFactory;

    protected $fillable = ['user_id', 'task_id', 'product_id', 'start_time', 'end_time', 'paused'];

    public function task(): HasOne
    {
        return $this->hasOne(Task::class, 'id', 'task_id');
    }

    public function user(): HasOne
    {
        return $this->hasOne(User::class, 'id', 'user_id');
    }

    public function getTimeForTimerAttribute(): string {
        $start_time = Carbon::parse($this->attributes['start_time']);

        /** Obtenemos tiempo pausado */
        $pauses_total = 0;
        $pauses = TrackingDetails::where('tracking_id', $this->id)
            ->whereNotNull('pause_time')
            ->whereNotNull('resume_time')
            ->get();
        foreach ($pauses as $pause) {
            $pause_time = strtotime($pause->pause_time);
            $resume_time = strtotime($pause->resume_time);
            $pauses_total += $resume_time - $pause_time;
        }

        $response = $start_time->addSeconds($pauses_total)->format('Y-m-d H:i:s');

        return $response;
    }

    public function getTimeAttribute(): int
    {
        $total = 0;

        /**
         * Obtenemos tiempo total
         */
        $start = strtotime($this->start_time);
        $end = strtotime($this->end_time);

        if ($this->paused) {
            $pause = TrackingDetails::where('tracking_id', $this->id)
                ->whereNotNull('pause_time')
                ->whereNull('resume_time')
                ->orderBy('id', 'desc')
                ->first();

            if ($pause) {
                $end = strtotime($pause->pause_time);
            }

        }

        $total = $end - $start;

        /**
         * Restamos tiempos de pausa
         */
        $pauses_total = 0;
        $pauses = TrackingDetails::where('tracking_id', $this->id)
            ->whereNotNull('pause_time')
            ->whereNotNull('resume_time')
            ->get();
        foreach ($pauses as $pause) {
            $pause_time = strtotime($pause->pause_time);
            $resume_time = strtotime($pause->resume_time);
            $pauses_total += $resume_time - $pause_time;
        }

        return $total - $pauses_total;
    }
}

resources/views/layouts/admin.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {{ seo()->render() }}

    @vite(['resources/css/app.css'])

</head>
<body class="page-{{ Route::current()->getName()  }}">

    <header id="header" class="site-header">
        <h1>{{__('Panel de administración')}}</h1>
    </header>

    <div class="dashboard">
        <nav class="dashboard__menu">

            <div class="dashboard__title">
                <label class="dashboard__title--label" for="menu">{{__('Menú')}}</label>
            </div>

            <input type="checkbox" class="dashboard__switch" id="menu">
            <ul class="dashboard__list dashboard__element-switch">
                <li><a href="{{ route('users') }}" class="dashboard__list--element link-icon link-icon--users {{ (request()->routeIs('users*')) ? 'active' : '' }}">{{__('Trabajadores')}}</a></li>
                <li><a href="{{ route('families') }}" class="dashboard__list--element link-icon link-icon--families {{ (request()->routeIs('families*')) ? 'active' : '' }}">{{__('Familias')}}</a></li>
                <li><a href="{{ route('products') }}" class="dashboard__list--element link-icon link-icon--products {{ (request()->routeIs('products*')) ? 'active' : '' }}">{{__('Productos')}}</a></li>
                <li><a href="{{ route('tasks') }}" class="dashboard__list--element link-icon link-icon--tasks {{ (request()->routeIs('tasks*')) ? 'active' : '' }}">{{__('Tareas')}}</a></li>
                <li><a href="{{ route('logout') }}" class="dashboard__list--element link-icon link-icon--logout">{{__('Salir')}}</a></li>
            </ul>
        </nav>

        @yield('content')

    </div>

    @if(Session::has('message'))
        <div class="message">{{ session('message') }}</div>
    @endif

</body>
</html>

resources/views/layouts/tracking.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}" />

    {{ seo()->render() }}

    @vite(['resources/css/app.css'])

</head>
<body class="page-{{ Route::current()->getName()  }}">

    @auth

        <header id="header" class="site-header">
            <h1>{{__('Tracking')}}</h1>

            <div class="menu">
                <label class="menu__button" for="menu"><span class="menu__button--dot"></span><span class="menu__button--dot"></span><span class="menu__button--dot"></span></label>
                <input class="menu__switch" type="checkbox" id="menu">
                <ul class="menu__submenu">

                    @if (Auth::user()->hasRole('Admin'))
                        <li><a href="{{ url('dashboard') }}">{{ __('Panel') }}</a></li>
                    @endif

                    <!-- <li><a href="#">{{ __('Mi cuenta') }}</a></li> -->
                    <li><a href="{{ url('logout') }}">{{ __('Salir') }}</a></li>

                </ul>
            </div>

        </header>

        <div class="user">
            <div class="user__label">{{ __('Trabajador/a') }}</div>
            <div class="user__name">{{ auth()->user()->name }}</div>
        </div>

    @endauth

    <div class="content">
        @yield('content')
    </div>

    @auth

        <footer class="site-fotoer">

        </footer>

    @endauth

    @vite(['resources/js/app.js'])

    <script>
        let start_time = @if (isset($actual_task))"{{ $actual_task->time_for_timer }}" @else null @endif;
    </script>

</body>
</html>